### ISSUE TITLE
Client bundle source path

### ISSUE THREAD

**Issue by kryopix** [express-vue/vue-pronto#105]
Hi,

is there a way to change the client bundle source path:

```js
<script src="/expressvue/bundles/index.vue.client.js"></script>
```
to this:

```js
<script src="./expressvue/bundles/index.vue.client.js"></script>
```

I didn't find a way to adjust the path to the correct route path.

I thank you in advance.

**Comment by danielcherubini** [comment]
you don't have to worry about that route.. expressvue handles that itself.

What are you trying to do?

**Comment by danielcherubini** [comment]
this is not going to change, since this path that it's getting is in memory-fs not real fs..
