### ISSUE TITLE
Migrate to Webpack

### ISSUE THREAD

**Issue by danielcherubini** [express-vue/vue-pronto#49]

**Comment by AlbertMarashi** [comment]
```
import Vue from "vue";
        import App from "C:\Users\XXXX\Desktop\repos\vue-t\tests\example\views\index\index.vue";

        export function createApp (data) {
            const app = new Vue({
                data,
                render: h => h(App)
            })
            return { app }
        }
```
the `${filePath}` is returning a unix string, so it doesn't work on windows it should be `/` rather than `\`

**Comment by AlbertMarashi** [comment]
Fixed with 
```
let importPath = filePath.replace(/\\/g,'\\\\')
        const parsedBundlePath = path.parse(filePath)
        const app = `import Vue from "vue";
        import App from "${importPath}";
        ...
```
not sure if it'll work on unix though

**Comment by danielcherubini** [comment]
No you use “path” go look at the node path docs. Don’t use a regex

**Comment by AlbertMarashi** [comment]
Unfortunately, that kept returning the same string, and the `\` would escape the next character. How can I prevent that?

**Comment by danielcherubini** [comment]
I don’t dev on Windows. And I don’t know if I’m going to finish this branch anytime soon. 

I’m having lunch and looking after my daughter this weekend so i don’t have time to look at this in depth.

**Comment by AlbertMarashi** [comment]
So how will the client bundle be served to the client? Why isn't it served inlined?
