### ISSUE TITLE
[opinion] i think you should use propsData instead of data 

### ISSUE THREAD

**Issue by akhoury** [express-vue/vue-pronto#66]
All the `data` being inserted into a Vue component is considered external or coming from outside or a parent of the component, hence, it should be considered as [`component.props`](https://vuejs.org/v2/api/#props) and not as [`component.data`](https://vuejs.org/v2/api/#data)

so, if `props` are used properly by each component definition, you can inject their values into a component instance via `propsData`

https://vuejs.org/v2/api/#propsData

I wasn't able to get this component to render, because it doesn't have a `data()` function, I know I can fix this simple component, but i do have a bunch of components that just accept `props` and i'd like to inject data into them.

```vue
<template>
  <p>Hi {{user && user.name}}</p>
</template>
<script>
  export default {
    props: ['user'],
  }
</script>
```

**Comment by danielcherubini** [comment]
I agree.. 

Also this is about to change in the eventual webpack renderer.. which will be using that vue global data object ...

THAT SAID

changing from data to props data would be a deprecation, and thus a v6 release. My goal going forward is to release a major version with a second rendering engine, and locking down the first rendering engine for bugfix only.

https://github.com/express-vue/vue-pronto/tree/feature/webpack

it's missing a few things, of which i have little time to work on.. I need about a week i guess.

Unless you wanna help.. then im all for that

**Comment by akhoury** [comment]
I created a PR that doesn't deprecate data, check it out, this is just I can use it till your webpack-renderer branch is published. 

Thanks

**Comment by akhoury** [comment]
awesome!
