### ISSUE TITLE
3 features/solutions request

### ISSUE THREAD

**Issue by akhoury** [express-vue/vue-pronto#69]
when you have a chance, please see this https://github.com/tj/consolidate.js/pull/265#issuecomment-420290486

the 3rd one, basically, it would be nice to just have a helper method, so I don't have to reach out to the `vueify` compiler and the `vue-server-renderer` 

```javascript
let html = await Pronto.renderFromStringToString(`<div>Hi {{ name }}</div>`, { name: 'Tobi' } )
console.log(html); // <div>Hi Tobi </div>
```

Thanks

**Comment by danielcherubini** [comment]
@akhoury 

in order

1. The performance will go so down if you disable cache.. like really really bad. why would you want to do that?

2. What's the output of this look like? i'm a little confused on this

3. there needs to be a rootpath otherwise you wont be able to find relative paths from that path.. for instance we have a structure like this

```
root
|- controllers/
|- middleware/
|- mixins/
|- components/
|- routes/
     |- foo/
         |- foo.vue
         |- foo.route.js
```
so we declare "routes" as rootpath, so when we say `renderVue("foo/foo.vue")` in foo.vue we can know that routes is root, so when pronto is looking for the files linked it can know exactly where they are, it's faster this way on the cpu.

It used to require full paths before, i then had to do some guessing.. this way is more explicit, and gives the user more freedom.

**Comment by akhoury** [comment]
hey, thanks for replying:

1) I agree with you, but in order to be added to the `consolidate.js` list, and pass its [tests](https://github.com/tj/consolidate.js/blob/78de9e8426e2bd8bd30ceaf4ad800851b89c24dc/test/shared/index.js#L26-L52), it needs to support disabling cache

2) this basically takes in a literal string `vue`ish template, with a `data` hash, and render it, just like almost any other template engine, from `string+data` to `string`

so for example, say we have a function `renderStringToString` 

```javascript
let output1 = await prontoRenderer.renderStringToString(
     `
      <h1 :class="name = 'Tobi' ? 'the-tobi-class' : 'the-unamed-class'">Hi {{ name }}</h1>
     `, 
      { name: 'Tobi' }
);

console.log(output1): // <h1 class="the-tobi-class">Hi Tobi</h1>
```

In `output1` example, I used 

```javascript
  var Component = { template: str, data: function() { return options; } };


  var Factory = vue.extend(Component); 
  var instance = new Factory({ propsData: options }); 
  // ssRenderer is created via the vue-server-renderer module
  ssRenderer.renderToString(instance, function(err, html) { 
     if (err) { 
       return cb(err); 
     } 
     cb(err, html); 
   }); 
```

Also support the full content of a `.vue` file, this probably needs to use `vueify.compiler.compile()` to create the component 

```javascript
let output2 = await prontoRenderer.renderStringToString(
     `
      <template><h1 :class="name = 'Tobi' ? 'the-tobi-class' : 'the-unamed-class'">Hi {{ name }}</h1></template>
     `, 
      { name: 'Tobi' }
);

console.log(output2): // <h1 class="the-tobi-class">Hi Tobi</h1>
```

In `output2` example, I used 

```javascript
vueify.compiler.compile(str, fullPath, function(err, js) { 
  var Component = requireFromString(js, fullPath);

  // code below same as the output1 example
  var Factory = vue.extend({ template: str, data: function() { return options; }); 
  var instance = new Factory({ propsData: options }); 
  // ssRenderer is created via the vue-server-renderer module
  ssRenderer.renderToString(instance, function(err, html) { 
     if (err) { 
       return cb(err); 
     } 
     cb(err, html); 
   });
}); 
```

**Comment by danielcherubini** [comment]
So disabling cache could use an environment variable or something?
it's common for some kind of test specific environment variable to be set by whatever runs the tests

**Comment by akhoury** [comment]
I would use a config property of the `Renderer` class, it's easier IMO, say `cache: false`, it would be `true` by default
